"""PCA Visualization with Confidence Ellipses.

This code generates and analyzes a 2D rotated Gaussian point cloud using PCA.
It demonstrates how PCA recovers the principal directions and variance of the data,
visualizing them along with 1-, 2-, and 3-standard deviation confidence ellipses.

The data is generated by:
1. Creating points with specified variances along principal axes
2. Rotating the points by π/3 radians
3. Translating to a specified center
"""

import matplotlib.pyplot as plt
import numpy as np

# Generate synthetic data
xC = np.array([2, 1])      # Center point for the cloud
sig = np.array([2, 0.5])   # Standard deviations along principal axes
theta = np.pi/3            # Rotation angle
R = np.array([[np.cos(theta), -np.sin(theta)],    # 2D rotation matrix
             [np.sin(theta), np.cos(theta)]])

# Create rotated and translated point cloud
nPoints = 10000
X = R @ np.diag(sig) @ np.random.randn(2,nPoints) + np.diag(xC) @ np.ones((2,nPoints))

# Plot raw data
plt.scatter(X[0,:], X[1,:], color='k')
plt.title('Raw Data')
plt.show()

# Center the data
Xavg = np.mean(X, axis=1)  # Compute centroid
B = X - Xavg[:, np.newaxis]  # Center the data

plt.plot(B[0,:],B[1,:], '.', color='k')
plt.title('Centered Data')
plt.show()

# Perform SVD for PCA
# Normalize by sqrt(nPoints) to get standard deviations as singular values
U, S, VT = np.linalg.svd(B/np.sqrt(nPoints), full_matrices=False)

print(U, R) # Notice how they are very similar 
print(S) # Sigma values recovered from the S matix

# Generate points for confidence ellipses
theta = 2 * np.pi * np.arange(0, 1, 0.01)
Xstd = U @ np.diag(S) @ np.array([np.cos(theta), np.sin(theta)])

# Plot confidence ellipses at 1, 2, and 3 standard deviations
plt.plot(Xavg[0] + Xstd[0,:], Xavg[1] + Xstd[1,:], '-', color='r', linewidth=3)
plt.plot(Xavg[0] + 2*Xstd[0,:], Xavg[1] + 2*Xstd[1,:], '-', color='r', linewidth=3)
plt.plot(Xavg[0] + 3*Xstd[0,:], Xavg[1] + 3*Xstd[1,:], '-', color='r', linewidth=3)

# Plot principal components
plt.plot(np.array([Xavg[0], Xavg[0]+U[0,0]*S[0]]),
        np.array([Xavg[1], Xavg[1]+U[1,0]*S[0]]), '-', color='cyan', linewidth=3)
plt.plot(np.array([Xavg[0], Xavg[0]+U[0,1]*S[1]]),
        np.array([Xavg[1], Xavg[1]+U[1,1]*S[1]]), '-', color='cyan', linewidth=3)

plt.show()